### ISSUE TITLE
List and set context

### ISSUE THREAD

**Issue by lucasfcosta** [ergomake/layerform#76]
- [ ] `layerform list contexts` -> prints all contexts saved on `~/.layerform/config`. If none, print message.
- [ ] `layerform set context` -> uses a context from the list to set as "current"

**Comment by SaumyaBhushan** [comment]
Hi @lucasfcosta! I am learning Golang. I want to work on this one, but I am a beginner in programming and in golang . Does it make sense to give it a shot? I think I would need a lot of help regarding this

**Comment by vieiralucas** [comment]
Hi @SaumyaBhushan.

This is definitely something harder than previous issues.

I think we could break this into 2 separated issues, one for the listing of contexts and other for changing what is the current context in use.

Also, since we created this issue we implemented `layerform config` command: https://github.com/ergomake/layerform/pull/84

I'll close this current issue in favor of #88 and #89.

I'll see if I have time in the coming days to add more guidance into how one could implement those issues.
